name: working_on_technics
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0

  path_provider: ^2.0.11
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #drift: ^1.7.1
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  get_storage: ^2.0.3

  # record and play audio
  flutter_sound_lite: ^8.5.0

  # file permissions
  permission_handler: ^9.2.0

  pdf: ^3.8.1
  printing: ^5.9.1
  open_file: ^3.2.1
  #advance_pdf_viewer: ^2.0.1

  my_auth:
    path: packages/my_auth

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  hive_generator: ^1.1.3
  #drift_dev: ^1.7.0
  build_runner: ^2.1.11

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/profiles/
    - assets/images/background/
